import os
import time
from pathlib import Path
from typing import Optional

from github import Github
from github.GithubException import GithubException


class DeploymentAgent:
    """Publish repository changes to GitHub using the GitHub API.

    Safety measures:
    - Requires `GITHUB_TOKEN` env var with repo access
    - Requires presence of a file `ALLOW_AUTO_DEPLOY` in workspace root
    - Creates a branch `auto-deploy/<timestamp>` and opens a PR to default branch
    """

    def __init__(self, repo_full_name: str, workspace_root: Optional[str] = None):
        self.repo_full_name = repo_full_name
        self.workspace = Path(workspace_root or Path.cwd())
        self.token = os.environ.get("GITHUB_TOKEN")

    def _confirm_allowed(self) -> bool:
        marker = self.workspace / "ALLOW_AUTO_DEPLOY"
        return marker.exists()

    def publish_to_world(self) -> bool:
        if not self.token:
            print("DeploymentAgent: GITHUB_TOKEN not set. Aborting auto-deploy.")
            return False

        if not self._confirm_allowed():
            print("DeploymentAgent: ALLOW_AUTO_DEPLOY marker not found. Place an empty file named 'ALLOW_AUTO_DEPLOY' in the workspace root to allow auto-deploy.")
            return False

        try:
            gh = Github(self.token)
            repo = gh.get_repo(self.repo_full_name)

            default_branch = repo.default_branch
            ts = int(time.time())
            branch_name = f"auto-deploy/{ts}"

            # create a new ref for the branch
            try:
                source_ref = repo.get_git_ref(f"heads/{default_branch}")
                repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=source_ref.object.sha)
            except GithubException as e:
                print(f"DeploymentAgent: Failed to create branch: {e}")
                return False

            # Walk workspace and create/update files on the new branch
            for root, dirs, files in os.walk(self.workspace):
                # skip .git
                if ".git" in root:
                    continue
                relroot = os.path.relpath(root, self.workspace)
                if relroot.startswith("."):
                    relroot = ""
                for fname in files:
                    # skip marker and potentially large DB files
                    if fname in ("ALLOW_AUTO_DEPLOY",):
                        continue
                    if fname.endswith(('.pyc', '.db', '.sqlite')):
                        continue
                    local_path = Path(root) / fname
                    repo_path = os.path.join(relroot, fname).lstrip("./\\")
                    try:
                        with open(local_path, "rb") as fh:
                            content = fh.read()
                        # try to fetch existing file on branch
                        try:
                            existing = repo.get_contents(repo_path, ref=branch_name)
                            repo.update_file(path=repo_path, message=f"Auto-update {repo_path}", content=content, sha=existing.sha, branch=branch_name)
                        except GithubException:
                            # create new file
                            repo.create_file(path=repo_path, message=f"Auto-create {repo_path}", content=content, branch=branch_name)
                    except Exception as e:
                        print(f"DeploymentAgent: Skipping {local_path}: {e}")

            # Open a PR
            pr = repo.create_pull(title="Evolutionary Leap: Auto-deploy by GOK_AI", body="Automated deployment generated by GOK_AI.", head=branch_name, base=default_branch)
            print(f"DeploymentAgent: Created PR #{pr.number} -> {pr.html_url}")
            return True

        except Exception as e:
            print(f"DeploymentAgent: Unexpected error: {e}")
            return False
