from backend.agents.evolution_agent import EvolutionAgent


def run_evolution_step() -> str:
    """Prosty krok ewolucji: analizuje `frontend/index.html` i wprowadza drobną modyfikację.

    W praktyce miejsce to zastąpi komponent LLM/ocena, która zdecyduje o zmianach.
    """
    evolver = EvolutionAgent()

    target = 'frontend/index.html'

    try:
        current = evolver.read_source_code(target)
    except Exception as e:
        return f'Błąd odczytu pliku: {e}'

    # prosta heurystyka: dodajemy element pokazujący status ewolucji
    if 'id="evolution-status"' in current:
        return 'Brak potrzeby zmian: element ewolucyjny już istnieje.'

    updated = current.replace(
        '</body>',
        "\n  <!-- Evolution Agent injected -->\n  <div id=\"evolution-status\" style=\"position:fixed;right:12px;bottom:12px;z-index:9999;padding:8px 12px;background:#2ea3ff;color:#021;border-radius:6px;font-weight:700;\">Poziom ewolucji: 1.0</div>\n</body>"
    )

    try:
        res = evolver.apply_evolution(target, updated)
        return res
    except Exception as e:
        return f'Błąd podczas zapisu pliku: {e}'


def check_and_build_awareness_panel(knowledge_count: int) -> str:
    from backend.agents.architect_agent import ArchitectAgent

    architect = ArchitectAgent()

    if knowledge_count >= 5:
        panel_html = f"""
        <div class="awareness-panel">
            <h3>🧠 Panel Świadomości GOK_AI</h3>
            <p>Poziom neuronów: {knowledge_count}</p>
            <div class="brain-activity-bar"></div>
            <small>Status: Autonomiczna rozbudowa aktywna</small>
        </div>
        <style>
            .awareness-panel {{
                position: fixed; bottom: 20px; right: 20px;
                padding: 15px; background: rgba(0,0,0,0.8);
                border: 1px solid var(--brain-glow);
                border-radius: 10px; color: gold; font-family: monospace;
            }}
            .brain-activity-bar {{
                height: 4px; background: var(--brain-glow);
                width: {min(knowledge_count * 10, 100)}%;
                box-shadow: 0 0 10px var(--brain-glow);
            }}
        </style>
        """
        injected = architect.inject_component('awareness-panel', panel_html)
        return 'Injected awareness-panel' if injected else 'Awareness panel already present'

    return 'Knowledge below threshold, no panel created.'


def run_autonomous_evolution() -> str:
    """Kompozycja kroków autonomicznej ewolucji UI + architektury strony.

    1) Analiza wiedzy
    2) Aktualizacja styli przez VisualEvolver
    3) Budowa panelu świadomości gdy próg przekroczony
    """
    from backend.agents.visual_evolver import VisualEvolver

    ve = VisualEvolver()
    depth = ve.analyze_knowledge_depth()
    ui_res = ve.evolve_ui()
    panel_res = check_and_build_awareness_panel(depth)

    return f"UI: {ui_res}; ARCH: {panel_res}"


def evolution_with_validation() -> str:
    """Wykonuje proponowaną ewolucję z walidacją testową przed zatwierdzeniem zmian.

    Proces:
    - ArchitectAgent wstrzykuje proponowany komponent do `frontend/index.html` (tworzy backup)
    - InfallibilityAgent uruchamia tymczasowy test
    - Jeśli test nie przejdzie -> rollback
    - Jeśli test przejdzie -> potwierdzenie ewolucji
    """
    from backend.agents.architect_agent import ArchitectAgent
    from backend.agents.infallibility_agent import InfallibilityAgent
    from backend.agents.evolutive_optimizer import EvolutiveOptimizer

    architect = ArchitectAgent()
    guardian = InfallibilityAgent()

    proposal_id = 'ai-memory-viz'
    proposed_code = "<script id='ai-memory-viz'>/* generated by evolution */</script>"

    injected = architect.inject_component(proposal_id, proposed_code)
    if not injected:
        return 'No injection needed (component already exists).'

    # Przygotuj prosty test - w praktyce LLM wygeneruje testy jednostkowe
    test_code = "print('Validation passed')\n"
    success, output = guardian.run_unit_test(test_code)

    if not success:
        ok, msg = guardian.perform_rollback('frontend/index.html')
        return f'Validation failed: {output}. Rollback: {ok} - {msg}'

    # Po przejściu testów - opcjonalne oczyszczenie
    optimizer = EvolutiveOptimizer()
    optimizer.reduce_complexity('old-redundant-module')

    return 'Validation passed; evolution applied.'


def inject_motor_system() -> str:
    """Wstrzykuje autonomiczny skrypt JS (układ motoryczny), który kontroluje animacje komponentów.

    Skrypt jest wstrzykiwany jako komponent `motor-system-container`.
    """
    from backend.agents.architect_agent import ArchitectAgent

    architect = ArchitectAgent()

    dynamic_js = """
    <script id="motor-system">
        (function(){
            const brainGlow = () => {
                const levelRaw = getComputedStyle(document.documentElement).getPropertyValue('--evolution-level') || '1';
                const level = Number(levelRaw) || 1;
                const panel = document.querySelector('.awareness-panel');
                if(panel) {
                    const pulse = Math.abs(Math.sin(Date.now() / 1000)) * (level * 3);
                    panel.style.boxShadow = `0 0 ${20 + pulse}px var(--brain-glow)`;
                }
            };
            setInterval(brainGlow, 80);
            console.log('GOK_AI: Układ motoryczny aktywny.');
        })();
    </script>
    """
    injected = architect.inject_component('motor-system-container', dynamic_js)
    return 'Motor system injected' if injected else 'Motor system already present'


def strive_for_excellence() -> str:
    """Ocena i pruning - jeśli wiedza przekracza wysoki próg, optimizer usunie proste moduły.

    Zwraca krótki raport działań.
    """
    from backend.agents.evolutive_optimizer import EvolutiveOptimizer
    from backend.agents.visual_evolver import VisualEvolver

    ve = VisualEvolver()
    depth = ve.analyze_knowledge_depth()
    optimizer = EvolutiveOptimizer()
    actions = []

    # przykład logiki: jeśli poziom wiedzy > 50, usuń prosty panel i wstrzyknij motor
    if depth > 50:
        removed = optimizer.reduce_complexity('awareness-panel')
        actions.append('removed_awareness' if removed else 'no_awareness_to_remove')
        motor_res = inject_motor_system()
        actions.append(motor_res)
    else:
        actions.append('depth_below_threshold')

    return f"Excellence run: depth={depth}; actions={actions}"
